# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Votre nom de workflow ici
on: [push]
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Nom de l'action ici 
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Nom de l'action ici 
        run: ./gradlew build
        
      - name : Nom de l'action ici 
        run: java -jar build/libs/*.jar 3 1
      
      - name: Nom de l'action ici 
        uses: actions/upload-artifact@v2
        with:
          name: Nom de votre artefact ici
          path: build/libs/*.jar
